services:
  postgres:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: rpgdb
#    volumes:
#      - '.localdata/postgresdb/:/var/lib/postgresql/data/'
