version: '3.8'
services:
  mongo:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    volumes:
      - '.localdata/mongo:/data/db'
  postgres:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: rpgdb
    volumes:
      - '.localdata/postgresdb/:/var/lib/postgresql/data/'
